### ISSUE TITLE
Next/Previous page buttons

### ISSUE THREAD

**Issue by bertt** [gost/dashboard#3]
Add Next/Previous page buttons

**Comment by justb4** [comment]
I just upgraded to `gost server` v0.5 and run `gost server` and the Dashboard separately via Docker. All is working, even the v1.0 backend proxy to the `gost server`.  But I do not see paging buttons for any STA Entity. Happens both in Dashboard `0.5` and `latest` and via an Apache Proxy or direct to port 8080. See below, is this the same issue? Remember seeing this before when Dashboard was part of `gost server`..How did we solve then? Aha, [I see it is still TODO](https://github.com/gost/server/issues/82#issuecomment-293901509).

![image](https://user-images.githubusercontent.com/582630/34307811-5014696c-e74a-11e7-9f1a-17598824a498.png)

**Comment by tebben** [comment]
Sorry for the late reply, we are currently working on a new dashboard https://github.com/gost/dashboard-v2, paging buttons will be available in this version
![dashboardv2](https://user-images.githubusercontent.com/6178776/34481726-fcb75a32-efb3-11e7-8f7c-7c0cda8ff49a.jpg)

**Comment by justb4** [comment]
Ok, good to hear! Also that you moved from NG to Web Components/Polymer. Will try Dashboard v2.
